from datetime import datetime
from typing import Final
from uuid import UUID

from bigdata_briefs.api.sql_models import SQLWorkflowStatus
from bigdata_briefs.sql_models import SQLBriefReport

EXAMPLE_UUID: Final[UUID] = UUID("11111111-1111-1111-1111-111111111112")

EXAMPLE_STATUS: Final[SQLWorkflowStatus] = SQLWorkflowStatus(
    id=EXAMPLE_UUID,
    last_updated=datetime.now(),
    status="completed",
    logs=[
        "Validating input parameters",
        "Generating report per entity",
        "Generated reports for 9 entities, 9 with information, 0 without information and 0 failed.",
        "Generating introduction section",
        "Introduction section generated",
        "Storing output report",
    ],
)

EXAMPLE_REPORT: Final[SQLBriefReport] = SQLBriefReport(
    id=EXAMPLE_UUID,
    watchlist_id="db8478c9-34db-4975-8e44-b1ff764098ac",
    created_at=datetime.now(),
    is_empty=False,
    report_period_start=datetime.fromisoformat("2025-10-01 00:00:00.000000"),
    report_period_end=datetime.fromisoformat("2025-10-07 00:00:00.000000"),
    novelty_enabled=True,
    brief_report={
        "watchlist_id": "db8478c9-34db-4975-8e44-b1ff764098ac",
        "watchlist_name": "AI Szn",
        "is_empty": False,
        "start_date": "2025-10-06T00:00:00",
        "end_date": "2025-10-06T00:00:00",
        "novelty": True,
        "report_title": "Broadcom Secures $10 Billion AI Rack Orders",
        "introduction": "* **Broadcom Inc.** secures over $10 billion in AI rack orders from a new customer, boosting fiscal 2026 AI revenue outlook to exceed $40 billion, with a projected 20% quarter-on-quarter growth in Q4 2025.\n\n* **Datadog Inc.** surpasses $100 million in annual recurring revenue for its security product suite, fueled by AI-driven tools, highlighting robust growth amid increasing cloud migration and digital transformation.\n\n* **NVIDIA Corp.** initiates a $60 billion share buyback program, reflecting strong confidence amid a 17% quarter-over-quarter surge in Blackwell Data Center revenue, despite rising competition in the AI chip market.\n\n* **Alphabet Inc.** commits $500 million to enhance regulatory compliance amid antitrust scrutiny, while increasing capital expenditures to $85 billion in 2025 to expand data centers and AI infrastructure, signaling aggressive growth despite legal challenges.\n\n* **Amazon.com Inc.** expands grocery delivery to over 1,000 cities with same-day service, aiming to double coverage by year-end, significantly enhancing its competitive edge in the $800 billion grocery market.\n\n* **Snowflake Inc.** strengthens its AI capabilities through strategic partnerships with GrowthLoop and Anthropic, enhancing data integration for clients like Indeed and NASCAR, positioning itself as a leader in advanced AI analytics.\n\n* **Microsoft Corp.** unbundles Teams from Office to address EU antitrust concerns, avoiding fines and enhancing interoperability, while laying off 9,000 employees to streamline costs and investing $400 million in AI and cloud capabilities in Switzerland.\n\n* **Palantir Technologies Inc.** achieves $2.79 billion in Q2 2025 sales, a 141% year-over-year increase, fueled by AI capabilities and a growing commercial segment, solidifying its market position.",
        "entity_reports": [
            {
                "entity_id": "09DE1F",
                "entity_info": {
                    "id": "09DE1F",
                    "name": "Broadcom Inc.",
                    "description": "Broadcom Inc. (formerly known as Broadcom Ltd.) designs, develops, and supplies semiconductor devices with a focus on analog III-V based products. The company was founded in August 2005. On February 1, 2016, Broadcom Corp. and Avago Technologies Ltd. merged to form Broadcom Ltd. (now Broadcom Inc.) The company redomiciled from Singapore to U.S. on April 4, 2018.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Technology",
                    "industry_group": "Semiconductors",
                    "industry": "Semiconductors",
                    "ticker": "AVGO",
                    "webpage": "http://www.broadcom.com",
                    "isin_values": [
                        "ARBCOM4603J5",
                        "CA11134P1009",
                        "TH0150122909",
                        "US11135F1012",
                    ],
                    "cusip_values": [
                        "11134P100",
                        "11135F101",
                        "P0R684690",
                        "Y49876371",
                    ],
                    "sedol_values": [
                        "B3Z2D24",
                        "BDZ78H9",
                        "BN6JCZ0",
                        "BRBGV35",
                        "BRF1S24",
                        "BZ1L8M4",
                    ],
                    "listing_values": [
                        "XBKK:AVGO80",
                        "XFRA:1YD",
                        "XLON:0YXG",
                        "XNAS:AVGO",
                        "XWBO:BROA",
                    ],
                },
                "content": [
                    {
                        "bullet_point": "**Broadcom Inc.** (AVGO) anticipates significant AI revenue growth in fiscal 2026, projecting over 40% increase driven by new customer orders and existing client expansion, with expected AI revenue exceeding $40 billion.",
                        "sources": [
                            "41734CC0418B23A3029EB2F2D9F73865-1",
                            "41734CC0418B23A3029EB2F2D9F73865-3",
                        ],
                    },
                    {
                        "bullet_point": "The company secured over $10 billion in AI rack orders from a new customer, enhancing its fiscal 2026 outlook for AI revenue, which is expected to rise over 20% quarter-on-quarter in Q4 2025.",
                        "sources": ["41734CC0418B23A3029EB2F2D9F73865-2"],
                    },
                    {
                        "bullet_point": "Broadcom is facing regulatory scrutiny in Europe regarding its $61 billion acquisition of VMware, as a cloud computing group challenges the deal's approval, citing potential market dominance and aggressive new licensing terms.",
                        "sources": [
                            "FA5088ED40E844381106356BA94E2ADD-1",
                            "FA5088ED40E844381106356BA94E2ADD-3",
                        ],
                    },
                    {
                        "bullet_point": "The company is deepening its strategic partnerships for AI infrastructure, including collaborations with OpenAI and NVIDIA, aimed at enhancing its capabilities in AI chip production and cloud services.",
                        "sources": ["0151FA370CE82B6D393EC840F29B174F-1"],
                    },
                    {
                        "bullet_point": "Broadcom announced a $10 billion share repurchase program through the end of 2025, reflecting confidence in its cash flow generation and commitment to delivering shareholder value.",
                        "sources": ["CEE040DD4CA610718693AB79AB744349-2"],
                    },
                ],
            },
            {
                "entity_id": "D6C356",
                "entity_info": {
                    "id": "D6C356",
                    "name": "Datadog Inc.",
                    "description": "Datadog Inc. is an IT company offering monitoring and analytics platform for modern cloud environments. The company was incorporated on the 4th of June 2010.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Technology",
                    "industry_group": "Software",
                    "industry": "Application Software",
                    "ticker": "DDOG",
                    "webpage": "http://www.datadoghq.com",
                    "isin_values": ["BRD1DGBDR001", "US23804L1035"],
                    "cusip_values": ["23804L103"],
                    "sedol_values": ["BKT9Y49", "BMXZ6N0"],
                    "listing_values": ["XNAS:DDOG"],
                },
                "content": [
                    {
                        "bullet_point": "Datadog's new AI features, including BITS AI agents for incident response and proactive coding assistance, are driving customer adoption, with over 4,500 customers utilizing AI integrations, indicating strong demand for next-gen observability solutions.",
                        "sources": [
                            "8C775796DDED1C2C8DA143E1E3BAB385-7",
                            "8C775796DDED1C2C8DA143E1E3BAB385-14",
                        ],
                    },
                    {
                        "bullet_point": "**Datadog Inc.** (DDOG) partners with Chainguard to enhance container security and observability, aiming to reduce risk across application surfaces amid a challenging market backdrop, with a 13% share price decline over the past week.",
                        "sources": ["A4FDD5A77435F4D769A0D56208FB2B37-9"],
                    },
                    {
                        "bullet_point": "The company recently joined the S&P 500 index on July 9, 2025, a significant milestone expected to boost stock visibility and attract passive fund inflows, enhancing its position in the cloud observability space.",
                        "sources": ["B6ADAC80E2C023FCB2B77D8252050A58-5"],
                    },
                    {
                        "bullet_point": "The company is addressing rising competition in the observability sector by expanding its platform capabilities and leveraging its AI product roadmap, which is expected to enhance deal flow for cloud migration and digital transformation projects.",
                        "sources": ["14D919146AD3751BECB87A391D76D73D-6"],
                    },
                    {
                        "bullet_point": "Datadog's security product suite has surpassed $100 million in annual recurring revenue, driven by the adoption of AI-driven security tools, reflecting strong growth expectations amid increasing cloud migration and digital transformation.",
                        "sources": ["8AEC78A4E987E1F84DDDD40466CBC09B-2"],
                    },
                ],
            },
            {
                "entity_id": "E09E2B",
                "entity_info": {
                    "id": "E09E2B",
                    "name": "NVIDIA Corp.",
                    "description": "NVIDIA Corp., incorporated in April 1993, designs, develops, and markets three dimensional (3D) graphics processors and related software. The Company offers products that provides interactive 3D graphics to the mainstream personal computer market as well as system on a chip units for the mobile computing and automotive market.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Technology",
                    "industry_group": "Semiconductors",
                    "industry": "Semiconductors",
                    "ticker": "NVDA",
                    "webpage": "http://www.nvidia.com",
                    "isin_values": [
                        "CA67080A1093",
                        "TH0150121000",
                        "TH0809121807",
                        "TH0842121509",
                        "TH8483122603",
                        "US67066G1040",
                    ],
                    "cusip_values": [
                        "67066G104",
                        "67080A109",
                        "P0R67N707",
                        "Y100G4386",
                        "Y476JC835",
                        "Y49876199",
                        "Y985HU589",
                    ],
                    "sedol_values": [
                        "2379504",
                        "B10S3Q7",
                        "BMGDF90",
                        "BP6LB42",
                        "BPLLR27",
                        "BVBM4Z4",
                        "BVF8ZL1",
                    ],
                    "listing_values": [
                        "XBKK:NVDA80",
                        "XETR:NVD",
                        "XFRA:NVD",
                        "XFRA:NVDG",
                        "XLOM:0R1I",
                        "XNAS:NVDA",
                    ],
                },
                "content": [
                    {
                        "bullet_point": "**NVIDIA Corp.** (NVDA) announces a $60 billion share buyback program, signaling strong confidence in its future despite a recent 17% increase in Blackwell Data Center revenue quarter-over-quarter, as stated by CEO Jensen Huang.",
                        "sources": ["4ADD163D75B3918879EAD3298B4ECB4A-2"],
                    },
                    {
                        "bullet_point": "The company faces increasing competition in the AI chip market, with a Citi analyst cutting its price forecast to $210 from $220, citing risks from Broadcom's $10 billion custom chip order and Google's growing traction with Tensor Processing Units.",
                        "sources": ["A768C79F90ABFE0FC831ADA9C83E2A66-5"],
                    },
                    {
                        "bullet_point": "NVIDIA is adapting to U.S. export restrictions by launching a significantly cheaper AI chip for the Chinese market, priced between $6,500 and $8,000, as it seeks to regain market share lost due to procurement bans.",
                        "sources": ["B917CB0BA5A2D247C9119C8AE91FE97C-1"],
                    },
                    {
                        "bullet_point": "The company successfully overcame supply chain challenges with TSMC, delivering its Blackwell AI servers to major cloud customers, including Microsoft, and confirming strong demand for AI chips amid ongoing production adjustments.",
                        "sources": ["CAB68AECFE656A24FDDB6C12ABAEB014-3"],
                    },
                ],
            },
            {
                "entity_id": "4A6F00",
                "entity_info": {
                    "id": "4A6F00",
                    "name": "Alphabet Inc.",
                    "description": "Alphabet Inc. (formerly Google Inc.) operates as a technology conglomerate, providing various services for people and businesses. It was founded on September 4, 1998. After a reorganization of Google on October 2, 2015, Alphabet Inc. became the parent company of Google and several former Google subsidiaries.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Technology",
                    "industry_group": "Internet Services",
                    "industry": "Internet Services",
                    "ticker": "GOOGL",
                    "webpage": "http://www.abc.xyz",
                    "isin_values": [
                        "ARDEUT116159",
                        "BRGOGLBDR001",
                        "BRGOGLBDR019",
                        "CA02080K1049",
                        "TH0150120903",
                        "TH0809121302",
                        "US02079K1079",
                        "US02079K2069",
                        "US02079K3059",
                        "US38259P2011",
                        "US38259P3001",
                        "US38259P4090",
                    ],
                    "cusip_values": [
                        "02079K107",
                        "02079K206",
                        "02079K305",
                        "02080K104",
                        "38259P201",
                        "38259P300",
                        "38259P409",
                        "P0R684351",
                        "Y100G4337",
                        "Y49876173",
                    ],
                    "sedol_values": [
                        "B043K04",
                        "BL25KS7",
                        "BNC31T3",
                        "BPLLP90",
                        "BVBCP40",
                        "BYV1PK4",
                        "BYV1PL5",
                        "BYVY8G0",
                        "BYY88Y7",
                    ],
                    "listing_values": [
                        "BVMF:GOGL34",
                        "BVMF:GOGL35",
                        "NEOE:GOOG",
                        "XBKK:GOOG80",
                        "XMEX:GOOGL",
                        "XNAS:GOOG",
                        "XNAS:GOOGL",
                        "XNMS:GOOG",
                    ],
                },
                "content": [
                    {
                        "bullet_point": "**Alphabet Inc.** (GOOGL) faces regulatory challenges following a recent antitrust ruling where a federal judge declined to force the sale of its Android operating system or Chrome browser, while mandating data sharing with competitors to enhance market competition.",
                        "sources": ["847BB10E2B1775363E80B7334C4B288B-11"],
                    },
                    {
                        "bullet_point": "The company is investing $500 million to enhance its global regulatory compliance structure as part of a resolution to a shareholder lawsuit related to U.S. antitrust allegations.",
                        "sources": ["C66C4028F577CB638A16C9569EF053E0-1"],
                    },
                    {
                        "bullet_point": "Alphabet plans to increase its capital expenditures to $85 billion for 2025, focusing on data center expansions and AI infrastructure to support both internal and external demands, indicating a strategic pivot towards growth despite regulatory pressures.",
                        "sources": ["7BF67423D8025C2D96028C4D2FEA794F-5"],
                    },
                    {
                        "bullet_point": "The cloud segment continues to show robust growth, with a 32% increase in sales and an operating margin expansion to 21%, although the company remains supply constrained as it builds out data centers to meet demand.",
                        "sources": ["D38B91991C8F89F937E95795803582E6-11"],
                    },
                ],
            },
            {
                "entity_id": "0157B1",
                "entity_info": {
                    "id": "0157B1",
                    "name": "Amazon.com Inc.",
                    "description": "Amazon.com Inc. is a multinational technology company focusing in e-commerce, cloud computing, and artificial intelligence. The company was incorporated on July 5, 1994.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Consumer Services",
                    "industry_group": "General Retailers",
                    "industry": "Internet & Direct Marketing Retail",
                    "ticker": "AMZN",
                    "webpage": "http://www.amazon.com",
                    "isin_values": [
                        "AU0000048530",
                        "CA02315E1051",
                        "TH0150121307",
                        "TH0809121401",
                        "TH0842120105",
                        "US0231351067",
                    ],
                    "cusip_values": [
                        "023135106",
                        "02315E105",
                        "P0R686174",
                        "Q3R79Y207",
                        "Y100G4345",
                        "Y476JC223",
                        "Y49876231",
                    ],
                    "sedol_values": [
                        "2000019",
                        "2436368",
                        "B01YWR1",
                        "B58WM62",
                        "BJ9K865",
                        "BNC31M6",
                        "BR1WCN0",
                        "BS7ZCZ2",
                        "BVBDDH2",
                    ],
                    "listing_values": [
                        "XBKK:AMZN01",
                        "XBKK:AMZN06",
                        "XBKK:AMZN80",
                        "XBOG:AMZN",
                        "XLIM:AMZN",
                        "XMEX:AMZN",
                        "XNAS:AMZN",
                        "XNMS:AMZN",
                    ],
                },
                "content": [
                    {
                        "bullet_point": "The company is under investigation by the FTC regarding its Prime subscription practices, accused of using deceptive user interface designs to mislead consumers into signing up and complicating cancellation processes, which could have significant implications for its revenue model.",
                        "sources": [
                            "1371BF3D4E067FABA429CF5E4E86EED0-1",
                            "1371BF3D4E067FABA429CF5E4E86EED0-2",
                        ],
                    },
                    {
                        "bullet_point": "**Amazon.com Inc.** (AMZN) faces ongoing scrutiny as shareholders voted against a proposal for a report on warehouse working conditions at its recent annual meeting, reflecting persistent concerns about operational practices and employee safety.",
                        "sources": ["04211BBDF32804844D5BB05D67D00D3F-6"],
                    },
                    {
                        "bullet_point": "Amazon is expanding its grocery delivery services significantly, rolling out same-day delivery of fresh food to over 1,000 cities, with plans to double this coverage by year-end, enhancing its competitive position in the grocery sector.",
                        "sources": ["7BA88ECD4CDDDD5F25FB6E5B7623B0EE-1"],
                    },
                    {
                        "bullet_point": "CEO Andy Jassy announced that Amazon's investments in artificial intelligence are expected to reduce the corporate workforce in the coming years, as efficiency gains from AI are anticipated to streamline operations.",
                        "sources": ["E898B75C55FA926D29A67AAF04A55993-1"],
                    },
                ],
            },
            {
                "entity_id": "D3D781",
                "entity_info": {
                    "id": "D3D781",
                    "name": "Snowflake Inc.",
                    "description": "Snowflake Inc. (formerly Snowflake Computing Inc.) is a cloud-based data-warehousing startup. The company was incorporated on July 23, 2012.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Technology",
                    "industry_group": "Software",
                    "industry": "Application Software",
                    "ticker": "SNOW",
                    "webpage": "http://www.snowflake.com",
                    "isin_values": [
                        "ARBCOM460358",
                        "BRS2NWBDR008",
                        "TH0842121202",
                        "US8334451098",
                    ],
                    "cusip_values": ["833445109", "P0R684559", "Y476JC801"],
                    "sedol_values": ["BL65618", "BN134B7", "BN6JCP0", "BVBM391"],
                    "listing_values": ["XNYS:SNOW"],
                },
                "content": [
                    {
                        "bullet_point": "**Snowflake Inc.** (SNOW) expands its AI strategy through partnerships with GrowthLoop and Anthropic, enhancing data integration and security for joint customers like Indeed and NASCAR, enabling agile marketing and advanced AI analytics.",
                        "sources": ["42C89172B57BB83E0E601300C1E932DF-4"],
                    },
                    {
                        "bullet_point": "The company is leading the Open Semantic Interchange initiative, aiming to standardize semantic metadata across platforms, addressing data fragmentation issues that hinder AI and BI applications.",
                        "sources": ["4172E6A42AFFF3F60B811FD0BDCA31E9-1"],
                    },
                    {
                        "bullet_point": "Snowflake's partnerships are critical for customer success in the AI era, as emphasized by industry leaders like Blue Yonder, highlighting the importance of a robust partner ecosystem for driving innovation and operational efficiency.",
                        "sources": [
                            "445EC4E37E08C6A8AB375AF050E3669D-6",
                            "445EC4E37E08C6A8AB375AF050E3669D-4",
                        ],
                    },
                ],
            },
            {
                "entity_id": "228D42",
                "entity_info": {
                    "id": "228D42",
                    "name": "Microsoft Corp.",
                    "description": "Microsoft Corp., is an American multinational software corporation headquartered in Redmond, Washington that develops, manufactures, licenses, and supports a wide range of products and services related to computing. The company was incorporated on June 25, 1981.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Technology",
                    "industry_group": "Software",
                    "industry": "Software",
                    "ticker": "MSFT",
                    "webpage": "http://www.microsoft.com",
                    "isin_values": [
                        "AU0000004574",
                        "CA59516M1041",
                        "TH0150121109",
                        "US5949181045",
                    ],
                    "cusip_values": [
                        "594918104",
                        "59516M104",
                        "P0R682363",
                        "Q3R79Y132",
                        "Y49876181",
                    ],
                    "sedol_values": [
                        "2588173",
                        "2668398",
                        "5925205",
                        "6257866",
                        "BGHHBL3",
                        "BPGZV88",
                        "BPLLQL9",
                    ],
                    "listing_values": [
                        "NEOE:MSFT",
                        "XHKG:04338",
                        "XHKG:4338",
                        "XMEX:MSFT",
                        "XNAS:MSFT",
                        "XNMS:MSFT",
                    ],
                },
                "content": [
                    {
                        "bullet_point": "Microsoft successfully addresses antitrust concerns by agreeing to unbundle its Teams platform from the Office suite, avoiding potential EU fines and enhancing interoperability with rival tools, a move that could reshape competitive dynamics in the productivity software market.",
                        "sources": [
                            "A2B4F5E18994360DA548C977466E7984-1",
                            "A2B4F5E18994360DA548C977466E7984-2",
                        ],
                    },
                    {
                        "bullet_point": "**Microsoft Corp.** (MSFT) initiates a second wave of layoffs impacting 9,000 employees, or less than 4% of its workforce, as part of a cost-control strategy while increasing investments in artificial intelligence.",
                        "sources": ["90A903485D244EC8AC4F537803314168-3"],
                    },
                    {
                        "bullet_point": "The company is investing $400 million to enhance its cloud and AI capabilities in Switzerland, expanding data centers near Zurich and Geneva as part of a broader strategy to capitalize on AI demand.",
                        "sources": ["6930737C9FBBB0192F409356F715F30D-1"],
                    },
                ],
            },
            {
                "entity_id": "F1C69A",
                "entity_info": {
                    "id": "F1C69A",
                    "name": "Palantir Technologies Inc.",
                    "description": "Palantir Technologies Inc. develops and builds data fusion platforms for integrating, managing, and securing any kind of data at massive scale. The company was incorporated in 2003 and is based in Palo Alto, California.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Technology",
                    "industry_group": "Data Processing & Outsourced Services",
                    "industry": "Data Processing & Outsourced Services",
                    "ticker": "PLTR",
                    "webpage": "http://www.palantir.com",
                    "isin_values": [
                        "AR0132889822",
                        "BRP2LTBDR001",
                        "CA7269161096",
                        "US69608A1088",
                    ],
                    "cusip_values": ["69608A108", "726916109", "P0R6A6536"],
                    "sedol_values": ["BLPK8M9", "BN78DQ4", "BPJGZB9", "BPTKWC1"],
                    "listing_values": ["XBUE:PLTR", "XNAS:PLTR"],
                },
                "content": [
                    {
                        "bullet_point": "**Palantir Technologies Inc.** (PLTR) partners with **Boeing Defense, Space & Security** to integrate AI into defense operations, enhancing production efficiency across multiple military manufacturing lines.",
                        "sources": ["D6AE11EB82D3779514479EBCB361FC44-3"],
                    },
                    {
                        "bullet_point": "The company reports a significant increase in new customer sales, closing $2.79 billion in Q2 2025, marking a 141% year-over-year growth, driven by its AI capabilities and expanding commercial segment.",
                        "sources": ["CFFDDC42775613C5F40E7CD71E23DDEB-5"],
                    },
                    {
                        "bullet_point": "Palantir's collaboration with Boeing includes undisclosed classified projects aimed at supporting sensitive military missions, reinforcing its position as a trusted provider in both government and commercial sectors.",
                        "sources": ["D6AE11EB82D3779514479EBCB361FC44-2"],
                    },
                ],
            },
            {
                "entity_id": "3A0C6D",
                "entity_info": {
                    "id": "3A0C6D",
                    "name": "MongoDB Inc.",
                    "description": "MongoDB Inc., formerly 10Gen Inc., develops internet infrastructure software. The company was incorporated on November 1, 2007 and is based in NY.",
                    "entity_type": "COMP",
                    "company_type": "Public",
                    "country": "United States",
                    "sector": "Technology",
                    "industry_group": "Software",
                    "industry": "Software",
                    "ticker": "MDB",
                    "webpage": "http://www.mongodb.com",
                    "isin_values": ["BRM1DBBDR001", "US60937P1066"],
                    "cusip_values": ["60937P106"],
                    "sedol_values": ["BF2FJ99", "BMXZ726"],
                    "listing_values": ["XNAS:MDB"],
                },
                "content": [
                    {
                        "bullet_point": "**MongoDB Inc.** (MDB) is strategically enhancing its AI integration capabilities, focusing on R&D and go-to-market initiatives to improve developer awareness and tooling related to application modernization and AI, while maintaining operating margins.",
                        "sources": ["AA6E7AE1225136AB75FACEA3CC8D603C-15"],
                    },
                    {
                        "bullet_point": "The company is addressing competitive pressures from **Snowflake** and **ServiceNow** by expanding its Atlas platform beyond database management into analytics, emphasizing developer-friendly interfaces and distributed architectures.",
                        "sources": ["17D930A64240A9A212340E58EE241179-6"],
                    },
                ],
            },
        ],
        "source_metadata": {
            "41734CC0418B23A3029EB2F2D9F73865-1": {
                "ref_id": 1,
                "document_id": "41734CC0418B23A3029EB2F2D9F73865",
                "headline": "Broadcom Set for Revenue Growth in Fiscal 2026 on AI Acceleration, Deutsche Bank Says",
                "ts": "2025-09-05T12:21:07+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "9D69F1",
                "source_name": "MT Newswires",
                "source_rank": 0,
                "url": None,
                "chunk_id": 1,
                "text": "08:21 AM EDT, 09/05/2025 (MT Newswires) -- Broadcom's (AVGO) comments on artificial intelligence that were provided as part of its fiscal Q3 results were bullish, Deutsche Bank analysts said in a note Friday, adding they expect its revenue in fiscal 2026 to rise by over 40% driven by AI revenue growth.",
                "highlights": [{"pnum": 1, "snum": 1}],
            },
            "41734CC0418B23A3029EB2F2D9F73865-2": {
                "ref_id": 2,
                "document_id": "41734CC0418B23A3029EB2F2D9F73865",
                "headline": "Broadcom Set for Revenue Growth in Fiscal 2026 on AI Acceleration, Deutsche Bank Says",
                "ts": "2025-09-05T12:21:07+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "9D69F1",
                "source_name": "MT Newswires",
                "source_rank": 0,
                "url": None,
                "chunk_id": 2,
                "text": "The technology company said that its AI revenue should rise over 20% quarter-on-quarter in fiscal Q4, and accelerate further in fiscal 2026 as it benefits from a higher share at its three original XPU AI chip customers and starts ramping up a newly-announced fourth customer, the note said.",
                "highlights": [{"pnum": 2, "snum": 1}],
            },
            "41734CC0418B23A3029EB2F2D9F73865-3": {
                "ref_id": 3,
                "document_id": "41734CC0418B23A3029EB2F2D9F73865",
                "headline": "Broadcom Set for Revenue Growth in Fiscal 2026 on AI Acceleration, Deutsche Bank Says",
                "ts": "2025-09-05T12:21:07+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "9D69F1",
                "source_name": "MT Newswires",
                "source_rank": 0,
                "url": None,
                "chunk_id": 3,
                "text": "Deutsche Bank said these aforementioned drivers should allow Broadcom to tap into its $110 billion backlog to yield AI revenue of over $40 billion in AI revenue in fiscal 2026.\nThe brokerage raised its price target to $350 from $300 and retained a buy rating on the stock.",
                "highlights": [{"pnum": 3, "snum": 1}, {"pnum": 4, "snum": 1}],
            },
            "FA5088ED40E844381106356BA94E2ADD-3": {
                "ref_id": 19,
                "document_id": "FA5088ED40E844381106356BA94E2ADD",
                "headline": "Broadcom's $61 Billion VMware Deal Faces EU Court Challenge - Could Regulatory Blowback Hit Growth?",
                "ts": "2025-07-25T15:13:09+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/46634755?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 3,
                "text": "The group claims the commission made serious legal and analytical errors by approving the deal without conditions, despite clear signs it could lead to market dominance and abuse.\nSince closing the acquisition, Broadcom has canceled existing contracts with minimal notice and imposed aggressive new licensing terms. These include price hikes of up to tenfold and mandatory multi-year commitments to access critical VMware software.",
                "highlights": [
                    {"pnum": 6, "snum": 1},
                    {"pnum": 7, "snum": 1},
                    {"pnum": 7, "snum": 2},
                ],
            },
            "FA5088ED40E844381106356BA94E2ADD-1": {
                "ref_id": 17,
                "document_id": "FA5088ED40E844381106356BA94E2ADD",
                "headline": "Broadcom's $61 Billion VMware Deal Faces EU Court Challenge - Could Regulatory Blowback Hit Growth?",
                "ts": "2025-07-25T15:13:09+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/46634755?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 1,
                "text": "Broadcom (NASDAQ:AVGO) is facing legal scrutiny over its $61 billion acquisition of VMware, as European Union judges assess a challenge to the deal's approval filed by a cloud computing group.\nCISPE, representing Europe's leading sovereign cloud infrastructure providers, filed a formal appeal on Thursday with the European General Court to challenge the European Commission's approval of the acquisition.",
                "highlights": [{"pnum": 1, "snum": 1}, {"pnum": 2, "snum": 1}],
            },
            "CEE040DD4CA610718693AB79AB744349-2": {
                "ref_id": 28,
                "document_id": "CEE040DD4CA610718693AB79AB744349",
                "headline": "Broadcom Inc. Announces $10 Billion Share Repurchase Authorization",
                "ts": "2025-04-07T20:21:04+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "D904DE",
                "source_name": "Associated Press",
                "source_rank": 0,
                "url": "https://apnews.com/press-release/pr-newswire/broadcom-inc-announces-10-billion-share-repurchase-authorization-c5eddf26f749d262e5174abe000ee8a0",
                "chunk_id": 2,
                "text": '"The new share repurchase program reflects the Board\'s confidence in our strong cash flow generation and allows us to deliver value to our stockholders," said Kirsten Spears, CFO of Broadcom Inc.\nRepurchases under the new share repurchase program may be made through a variety of methods, including open market or privately negotiated purchases. The timing and amount of shares repurchased will depend on the stock price, business and market conditions, corporate and regulatory requirements, alternative investment opportunities, acquisition opportunities and other factors. Broadcom is not obligated to repurchase any specific amount of shares of common stock, and the share repurchase program may be suspended or terminated at any time.',
                "highlights": [
                    {"pnum": 3, "snum": 1},
                    {"pnum": 4, "snum": 1},
                    {"pnum": 4, "snum": 2},
                    {"pnum": 4, "snum": 3},
                ],
            },
            "0151FA370CE82B6D393EC840F29B174F-1": {
                "ref_id": 33,
                "document_id": "0151FA370CE82B6D393EC840F29B174F",
                "headline": "Broadcom Ramps Up AI Ambitions With High-Stakes OpenAI Deal",
                "ts": "2025-09-08T14:17:12+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/47548649?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 1,
                "text": "Broadcom (NASDAQ:AVGO) has evolved from a smartphone component supplier into a major player in artificial intelligence chips and networking solutions, capitalizing on rising demand from tech giants building large-scale data centers. The stock gained attention Monday following reports of its partnership with OpenAI.",
                "highlights": [{"pnum": 1, "snum": 1}, {"pnum": 1, "snum": 2}],
            },
            "42C89172B57BB83E0E601300C1E932DF-4": {
                "ref_id": 1,
                "document_id": "42C89172B57BB83E0E601300C1E932DF",
                "headline": 'GrowthLoop Recognized as "One to Watch" in Snowflake\'s 2026 Modern Marketing Data Stack Report',
                "ts": "2025-09-30T17:01:30+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/47949893?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 4,
                "text": '"GrowthLoop enables marketers to activate and optimize their campaigns directly within the Snowflake AI Data Cloud, helping them experiment and iterate at scale," said Denise Persson, Chief Marketing Officer at Snowflake. "We\'re excited to continue partnering with GrowthLoop to help marketers move with greater agility and deliver lasting impact."\nGrowthLoop is delivering measurable results through seamless collaboration and data integration. The company\'s deep integration within the Snowflake AI Data Cloud breaks down traditional barriers like siloed data and slow cycles. Ultimately, this allows their joint customers - including Indeed, NASCAR, and HBSE - to quickly build audiences, automate lifecycle campaigns, and measure performance across owned channels securely and at scale.',
                "highlights": [
                    {"pnum": 6, "snum": 1},
                    {"pnum": 6, "snum": 2},
                    {"pnum": 7, "snum": 1},
                    {"pnum": 7, "snum": 2},
                    {"pnum": 7, "snum": 3},
                ],
            },
            "4172E6A42AFFF3F60B811FD0BDCA31E9-1": {
                "ref_id": 4,
                "document_id": "4172E6A42AFFF3F60B811FD0BDCA31E9",
                "headline": "Snowflake, Salesforce, dbt Labs, and More, Revolutionize Data Readiness for AI with Open Semantic Interchange Initiative",
                "ts": "2025-09-23T13:11:39+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "D904DE",
                "source_name": "Associated Press",
                "source_rank": 0,
                "url": "https://apnews.com/press-release/business-wire/snowflake-salesforce-dbt-labs-and-more-revolutionize-data-readiness-for-ai-with-open-semantic-interchange-initiative-518b6333eb774ddc9861094dfe20d409",
                "chunk_id": 1,
                "text": "Snowflake (NYSE: SNOW), the AI Data Cloud company in partnership with leading industry partners and ecosystem vendors, including Salesforce, BlackRock, dbt Labs, and RelationalAI, announced a bold commitment to lead the Open Semantic Interchange (OSI), a new open source initiative. In today's AI era, fragmented data semantics across tools and platforms create a major roadblock for both human and AI-enabled analysis. This initiative addresses that challenge head-on by introducing a common, vendor-neutral semantic model specification that standardizes how semantic metadata is defined and shared - ensuring consistent business logic across AI and business intelligence (BI) applications.",
                "highlights": [
                    {"pnum": 2, "snum": 1},
                    {"pnum": 2, "snum": 2},
                    {"pnum": 2, "snum": 3},
                ],
            },
            "445EC4E37E08C6A8AB375AF050E3669D-4": {
                "ref_id": 5,
                "document_id": "445EC4E37E08C6A8AB375AF050E3669D",
                "headline": "Snowflake Appoints Chris Niederman as Alliances & Channels Leader",
                "ts": "2025-07-10T13:05:00+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/46342096?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 4,
                "text": '"Throughout my career, I\'ve seen how a thriving partner ecosystem and partner-led growth directly impact customer success," said Niederman. "Snowflake\'s partners are at the forefront of innovation, extending the power of the AI Data Cloud and enabling our joint customers to unlock maximum value from their data and drive business outcomes. I look forward to getting to work, meeting our partners and customers in the field, and deepening these critical relationships to accelerate our joint successes."',
                "highlights": [
                    {"pnum": 5, "snum": 1},
                    {"pnum": 5, "snum": 2},
                    {"pnum": 5, "snum": 3},
                ],
            },
            "445EC4E37E08C6A8AB375AF050E3669D-6": {
                "ref_id": 6,
                "document_id": "445EC4E37E08C6A8AB375AF050E3669D",
                "headline": "Snowflake Appoints Chris Niederman as Alliances & Channels Leader",
                "ts": "2025-07-10T13:05:00+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/46342096?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 6,
                "text": "\"Partnering with Snowflake is critical to our customers' success especially in the AI era. I've seen the business impact Chris can drive first-hand after our many years working together across the tech ecosystem. Chris's deep experience in fostering strategic alliances and his focus on impactful industry solutions will expand the Snowflake ecosystem's capabilities and empower joint customers to accelerate their supply chain operations with AI at the core.\" Darren Saumur, President, Blue Yonder",
                "highlights": [
                    {"pnum": 8, "snum": 1},
                    {"pnum": 8, "snum": 2},
                    {"pnum": 8, "snum": 3},
                    {"pnum": 8, "snum": 4},
                ],
            },
            "90A903485D244EC8AC4F537803314168-3": {
                "ref_id": 1,
                "document_id": "90A903485D244EC8AC4F537803314168",
                "headline": "Sector Update: Tech Stocks Gain Wednesday Afternoon",
                "ts": "2025-07-02T17:56:10+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "9D69F1",
                "source_name": "MT Newswires",
                "source_rank": 0,
                "url": None,
                "chunk_id": 3,
                "text": 'Microsoft (MSFT) started a second wave of layoffs that will impact 9,000 workers, or less than 4% of the company\'s total workforce, Bloomberg reported. Separately, Microsoft plans to focus on "less-ambitious" designs for its AI chips through 2028 as it works to address development delays, The Information reported. Microsoft shares were down 0.4%.',
                "highlights": [
                    {"pnum": 4, "snum": 1},
                    {"pnum": 4, "snum": 2},
                    {"pnum": 4, "snum": 3},
                ],
            },
            "A2B4F5E18994360DA548C977466E7984-1": {
                "ref_id": 9,
                "document_id": "A2B4F5E18994360DA548C977466E7984",
                "headline": "How Microsoft avoided a billion-dollar EU fine over Teams",
                "ts": "2025-09-12T12:30:43+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "80FC03",
                "source_name": "The Times Of India",
                "source_rank": 2,
                "url": "https://timesofindia.indiatimes.com/technology/tech-news/how-microsoft-avoided-a-billion-dollar-eu-fine-over-teams/articleshow/123852408.cms",
                "chunk_id": 1,
                "text": "Microsoft has successfully averted a substantial EU fine by agreeing to unbundle Teams from its Office suite, addressing antitrust concerns raised by competitors like Slack and alfaview. The company will offer reduced pricing for Office without Teams and enhance interoperability with rival communication tools. This seven-year commitment aims to foster competition and empower businesses to choose the best collaboration platform. Microsoft has successfully avoided a potentially hefty European Union fine, which could have amounted to billions of dollars, by agreeing to unbundle its Teams platform from Office productivity software and offer reduced pricing options.",
                "highlights": [
                    {"pnum": 1, "snum": 1},
                    {"pnum": 1, "snum": 2},
                    {"pnum": 1, "snum": 3},
                    {"pnum": 1, "snum": 4},
                ],
            },
            "A2B4F5E18994360DA548C977466E7984-2": {
                "ref_id": 10,
                "document_id": "A2B4F5E18994360DA548C977466E7984",
                "headline": "How Microsoft avoided a billion-dollar EU fine over Teams",
                "ts": "2025-09-12T12:30:43+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "80FC03",
                "source_name": "The Times Of India",
                "source_rank": 2,
                "url": "https://timesofindia.indiatimes.com/technology/tech-news/how-microsoft-avoided-a-billion-dollar-eu-fine-over-teams/articleshow/123852408.cms",
                "chunk_id": 2,
                "text": "The European Commission says it accept Microsoft's commitments to address antitrust concerns, ending a years-long investigation that began with complaints from competitors. The case originated from a 2020 complaint filed by Salesforce-owned Slack, which accused Microsoft of illegally bundling Teams with Office 365 and Microsoft 365 to gain unfair competitive advantage. German competitor alfaview filed a similar complaint in 2023, intensifying regulatory scrutiny. Under the binding agreement, Microsoft will make Office 365 and Microsoft 365 versions available without Teams at prices reduced by 1 to 8 euros. The company has also committed to widening the price gap between bundled and unbundled versions by 50% for certain business-focused suites. The commitments extend beyond pricing changes.",
                "highlights": [
                    {"pnum": 1, "snum": 5},
                    {"pnum": 1, "snum": 6},
                    {"pnum": 1, "snum": 7},
                    {"pnum": 1, "snum": 8},
                    {"pnum": 1, "snum": 9},
                    {"pnum": 1, "snum": 10},
                ],
            },
            "6930737C9FBBB0192F409356F715F30D-1": {
                "ref_id": 14,
                "document_id": "6930737C9FBBB0192F409356F715F30D",
                "headline": "Microsoft to Invest $400 Million in Switzerland to Strengthen Cloud, AI Capabilities",
                "ts": "2025-06-02T11:56:16+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "9D69F1",
                "source_name": "MT Newswires",
                "source_rank": 0,
                "url": None,
                "chunk_id": 1,
                "text": "07:56 AM EDT, 06/02/2025 (MT Newswires) -- Microsoft (MSFT) said Monday it is investing $400 million to bolster its cloud and artificial intelligence capabilities in Switzerland.\nThe technology giant said it will expand its existing data centers near Zurich and Geneva and form a partnership with Switzerland Innovation Parks and its sites as part of the initiative.",
                "highlights": [{"pnum": 1, "snum": 1}, {"pnum": 2, "snum": 1}],
            },
            "D6AE11EB82D3779514479EBCB361FC44-2": {
                "ref_id": 1,
                "document_id": "D6AE11EB82D3779514479EBCB361FC44",
                "headline": "Palantir, Boeing Join Forces To Accelerate AI In Defense And Space Units: 'America's Enemies Aren't Slowing Down...'",
                "ts": "2025-09-24T07:53:52+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/47835522?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 2,
                "text": "Additionally, BDS has engaged Palantir to deliver AI expertise for several undisclosed, classified projects aimed at supporting military customers' most sensitive missions.\nCheck out the current price of PLTR stock here.\nBoeing Defense Systems is responsible for the production of military aircraft, helicopters, satellites, spacecraft, missiles, and weapons.\nMike Gallagher, Palantir's Head of Defense, said, \"This partnership will turbocharge production and innovation... America's enemies aren't slowing down and neither can we.\"",
                "highlights": [
                    {"pnum": 4, "snum": 1},
                    {"pnum": 5, "snum": 1},
                    {"pnum": 6, "snum": 1},
                    {"pnum": 7, "snum": 1},
                    {"pnum": 7, "snum": 2},
                ],
            },
            "D6AE11EB82D3779514479EBCB361FC44-3": {
                "ref_id": 2,
                "document_id": "D6AE11EB82D3779514479EBCB361FC44",
                "headline": "Palantir, Boeing Join Forces To Accelerate AI In Defense And Space Units: 'America's Enemies Aren't Slowing Down...'",
                "ts": "2025-09-24T07:53:52+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/47835522?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 3,
                "text": "Boeing Deal Could Strengthen Palantir's Position\nThis partnership comes at a time when Boeing is expanding its deal pipeline with major jet purchases eyed by Kazakhstan, Turkey, and China. This collaboration with Palantir could further strengthen Boeing's position in the aerospace and defense market.\nAt the same time, BofA kept a Buy rating on Palantir and raised its price target to $215, citing AI-driven growth and international expansion. The update follows Palantir's first billion-dollar U.K. deal with the Ministry of Defence, marking a major step in its global defense analytics strategy.",
                "highlights": [
                    {"pnum": 8, "snum": 1},
                    {"pnum": 9, "snum": 1},
                    {"pnum": 9, "snum": 2},
                    {"pnum": 10, "snum": 1},
                    {"pnum": 10, "snum": 2},
                ],
            },
            "CFFDDC42775613C5F40E7CD71E23DDEB-5": {
                "ref_id": 3,
                "document_id": "CFFDDC42775613C5F40E7CD71E23DDEB",
                "headline": "Tech Corner: Palantir's Place in the A.I. Trade",
                "ts": "2025-10-04T17:00:00+00:00",
                "document_scope": "transcripts",
                "language": "English",
                "source_key": "CE6D92",
                "source_name": "Schwab Network",
                "source_rank": 1,
                "url": "https://anchor.fm/s/f589d064/podcast/play/109181438/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-9-3%2F408622003-44100-2-aa4f044b273e6.mp3",
                "chunk_id": 5,
                "text": "while closing $2 .79 billion in new customer sales, up 141 % year -over -year, as the company continues to capitalize on AI production use cases. Now, in late September last month, Boeing said it was joining forces with Palantir to integrate artificial intelligence into its defense space and security business. Its BDS unit would use Palantir's Foundry platform to standardize data analytics and insights across its geographically dispersed defense factories. Now, when looking at Palantir, there a lot of positives to consider. First off, the company is positioned to join tech giants due to its government ties and rapid artificial intelligence platform growth, offering high margins and strong cash flow potential. As I mentioned earlier, Palantir's U .S. commercial segment is a key growth driver for the business, considering it started off as a defense contracting business. It was up 93 % year -by -year with that contract bookings up 222%. This again indicates strong market traction and forward revenue visibility. The company demonstrates outstanding growth.",
                "highlights": [
                    {"pnum": 7, "snum": 1},
                    {"pnum": 7, "snum": 2},
                    {"pnum": 7, "snum": 3},
                    {"pnum": 7, "snum": 4},
                    {"pnum": 7, "snum": 5},
                    {"pnum": 7, "snum": 6},
                    {"pnum": 7, "snum": 7},
                    {"pnum": 7, "snum": 8},
                    {"pnum": 7, "snum": 9},
                ],
            },
            "A4FDD5A77435F4D769A0D56208FB2B37-9": {
                "ref_id": 2,
                "document_id": "A4FDD5A77435F4D769A0D56208FB2B37",
                "headline": "Chainguard Raises $356 Million in Series D Funding to Be the Safe Source for All Open Source",
                "ts": "2025-04-23T12:15:07+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/44946976?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 9,
                "text": '"Chainguard is at the forefront of setting the industry standard for secure-by-default infrastructure," said Nowi Kallen, Managing Director, Salesforce Ventures. "We\'re excited to support the company\'s growth as its solutions become an essential foundation for security and compliance at scale, and its teams redefine how organizations safeguard their most critical applications."\n"Modern organizations need access to secure software that is seamlessly integrated into their development workflows," said Bharat Sajnani, Senior Vice President, Head of Corporate Development and Ventures, Datadog. "Every day, Chainguard is helping organizations build software better and make the most of their engineering resources. This partnership builds on Datadog\'s integration with Chainguard to help customers reduce risk across their application surface area, and we\'re excited to continue on this journey with them."',
                "highlights": [
                    {"pnum": 15, "snum": 1},
                    {"pnum": 15, "snum": 2},
                    {"pnum": 16, "snum": 1},
                    {"pnum": 16, "snum": 2},
                    {"pnum": 16, "snum": 3},
                ],
            },
            "B6ADAC80E2C023FCB2B77D8252050A58-5": {
                "ref_id": 3,
                "document_id": "B6ADAC80E2C023FCB2B77D8252050A58",
                "headline": "Why Datadog (DDOG) Stock Is Trading Lower Today",
                "ts": "2025-07-08T18:00:45+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "E5AA62",
                "source_name": "Yahoo! Finance",
                "source_rank": 2,
                "url": "https://uk.finance.yahoo.com/news/why-datadog-ddog-stock-trading-175059716.html",
                "chunk_id": 5,
                "text": "The change is scheduled to be effective before the market opens on July 9. Inclusion in the S&P 500 is a significant milestone for a company, often leading to a surge in demand for its stock. This is because index funds and exchange-traded funds (ETFs) that track the S&P 500 are now required to purchase Datadog shares to align their holdings with the index's new composition. This automatic buying pressure from passive investment funds is a primary driver for the stock's sharp increase. The move also enhances the company's visibility and solidifies its position as a major player in the cloud observability space.",
                "highlights": [
                    {"pnum": 7, "snum": 1},
                    {"pnum": 7, "snum": 2},
                    {"pnum": 7, "snum": 3},
                    {"pnum": 7, "snum": 4},
                    {"pnum": 7, "snum": 5},
                ],
            },
            "8C775796DDED1C2C8DA143E1E3BAB385-7": {
                "ref_id": 9,
                "document_id": "8C775796DDED1C2C8DA143E1E3BAB385",
                "headline": "Datadog Q2 FY2025 Earnings Call Transcript",
                "ts": "2025-08-07T14:00:07+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/46963722?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 7,
                "text": "While we are pleased to achieve this milestone, we're still just getting started in solving customer problems in this area with new innovations such as our best AI Security capabilities. Moving on to R and D, we held our Dash user conference in June where we announced over 125 exciting new products and features for our users. So let's go through some of the announcements. First, we launched fully autonomous AI agents including BITS AI SRE Agent to investigate alerts in coordinate incident response BITS AI Dave Agent, an AI powered coding Assistant to proactively fix production issues and BITS AI Security Analyst to triage and adopt Cloud SIEM signals to further accelerate our users incident response. We announced AI Voice Agent for incident response so users can quickly get up to speed and start taking action on their phones. We also announced handoff notifications that make it easy to jump straight into the relevant context and quickly communicate with our responders and status pages to enable automatic updates for customers undergoing incident. Second, we delivered a series of products to help customers ship better software with confidence with the datadog internal developer portal.",
                "highlights": [
                    {"pnum": 10, "snum": 16},
                    {"pnum": 10, "snum": 17},
                    {"pnum": 10, "snum": 18},
                    {"pnum": 10, "snum": 19},
                    {"pnum": 10, "snum": 20},
                    {"pnum": 10, "snum": 21},
                    {"pnum": 10, "snum": 22},
                ],
            },
            "8C775796DDED1C2C8DA143E1E3BAB385-14": {
                "ref_id": 12,
                "document_id": "8C775796DDED1C2C8DA143E1E3BAB385",
                "headline": "Datadog Q2 FY2025 Earnings Call Transcript",
                "ts": "2025-08-07T14:00:07+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/46963722?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 14,
                "text": "First, AI is a tailwind for Datadog as increased cloud consumption drives more usage of our platform. Today we see this primarily in our AI native group of customers who are monitoring their cloud native applications with us. There are hundreds of customers in this group. They include more than a dozen that are spending over a million dollars a year with us and more than 80 who are spending more than $100,000. And they include eight of the top 10 leading AI companies. While we know there's a lot of attention on this cohort, we primarily see it as an indication of what's to come as companies of every size and every single industry incorporate AI into their cloud applications. And we continue to see rising customer interest for next gen AI observability and analysis. Today over 4,500 customers use one or more Datadog AI integrations. Second, NextGen AI introduces new complexity and new observability challenges. Our AI observability products help our customers gain visibility and deploy with confidence across their entire AI stack including GPU monitoring, LLM observability, AI Agent, observability and data. And we will of course keep innovating as the AI landscape develops further.",
                "highlights": [
                    {"pnum": 10, "snum": 69},
                    {"pnum": 10, "snum": 70},
                    {"pnum": 10, "snum": 71},
                    {"pnum": 10, "snum": 72},
                    {"pnum": 10, "snum": 73},
                    {"pnum": 10, "snum": 74},
                    {"pnum": 10, "snum": 75},
                    {"pnum": 10, "snum": 76},
                    {"pnum": 10, "snum": 77},
                    {"pnum": 10, "snum": 78},
                    {"pnum": 10, "snum": 79},
                ],
            },
            "8AEC78A4E987E1F84DDDD40466CBC09B-2": {
                "ref_id": 16,
                "document_id": "8AEC78A4E987E1F84DDDD40466CBC09B",
                "headline": "Datadog's Q2 Revenue Rises on Customer Expansion, Multi-Product Adoption, Wedbush Says",
                "ts": "2025-08-08T14:47:09+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "9D69F1",
                "source_name": "MT Newswires",
                "source_rank": 0,
                "url": None,
                "chunk_id": 2,
                "text": "The security product suite surpassed $100 million in annual recurring revenue as customers adopted new offerings, including artificial intelligence-driven security tools, according to the note.\nThe company increased its full-year revenue guidance on growth expectations due to cloud migration, digital transformation, and increasing AI adoption across small-to-medium business, mid-market, and enterprise clients, Wedbush said.",
                "highlights": [{"pnum": 2, "snum": 1}, {"pnum": 3, "snum": 1}],
            },
            "14D919146AD3751BECB87A391D76D73D-6": {
                "ref_id": 20,
                "document_id": "14D919146AD3751BECB87A391D76D73D",
                "headline": "Datadog's S&P 500 Inclusion Validates Continued Momentum in Observability Space, Wedbush Says",
                "ts": "2025-07-03T10:29:57+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "9D69F1",
                "source_name": "MT Newswires",
                "source_rank": 0,
                "url": None,
                "chunk_id": 6,
                "text": "Datadog is well placed to continue to gain market share within the observability space, amid high usage of its AI offerings across an enterprise consumer base, the brokerage said. The company's new go-to-market motion is expected to lead to more deal flow for cloud migration monitoring and digital transformation projects, Ives added.",
                "highlights": [{"pnum": 8, "snum": 1}, {"pnum": 8, "snum": 2}],
            },
            "4ADD163D75B3918879EAD3298B4ECB4A-2": {
                "ref_id": 1,
                "document_id": "4ADD163D75B3918879EAD3298B4ECB4A",
                "headline": "Nvidia Stock Falls Over 2% In Thursday Pre-Market, Dan Ives Says Any Decline Is A Clear 'Buying Opportunity'",
                "ts": "2025-08-28T10:16:43+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/47379583?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 2,
                "text": "Nvidia's Blackwell Data Center revenue experienced a 17% increase quarter-over-quarter. CEO Jensen Huang highlighted the company's AI platform, Blackwell, as a significant leap forward. He stated, \"The AI race is on, and Blackwell is the platform at its center.\"\nAlongside the earnings, Nvidia announced a new $60 billion share buyback authorization, with $14.7 billion still available from an existing repurchase agreement.",
                "highlights": [
                    {"pnum": 4, "snum": 1},
                    {"pnum": 4, "snum": 2},
                    {"pnum": 4, "snum": 3},
                    {"pnum": 5, "snum": 1},
                ],
            },
            "A768C79F90ABFE0FC831ADA9C83E2A66-5": {
                "ref_id": 9,
                "document_id": "A768C79F90ABFE0FC831ADA9C83E2A66",
                "headline": "Nvidia Launches New Chip To Boost AI Coding And Video Tools",
                "ts": "2025-09-09T16:51:15+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/47577111?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 5,
                "text": "However, Citi analyst Atif Malik cut Nvidia's price forecast to $210 from $220, warning that rising AI chip competition will weigh on future sales. He cited Broadcom's (NASDAQ:AVGO) $10 billion custom chip order and growing traction with Alphabet (NASDAQ:GOOGL) Google's Tensor Processing Units (TPUs) as key risks, predicting Nvidia's 2026 GPU sales could fall about 4% below prior estimates.",
                "highlights": [{"pnum": 7, "snum": 1}, {"pnum": 7, "snum": 2}],
            },
            "CAB68AECFE656A24FDDB6C12ABAEB014-3": {
                "ref_id": 14,
                "document_id": "CAB68AECFE656A24FDDB6C12ABAEB014",
                "headline": "Nvidia Hits $4 Trillion Market Cap, Stock Surges To All-Time High",
                "ts": "2025-07-09T14:37:16+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/46321541?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 3,
                "text": "This endorsement helps solidify Nvidia's position as the foundational hardware provider for the world's leading AI models. Further bolstering sentiment is the passing of the \"Big Beautiful Bill,\" which aims to increase the U.S. semiconductor investment tax credit, and news that key supplier TSMC is accelerating its American expansion, shoring up Nvidia's supply chain.",
                "highlights": [{"pnum": 3, "snum": 1}, {"pnum": 3, "snum": 2}],
            },
            "B917CB0BA5A2D247C9119C8AE91FE97C-1": {
                "ref_id": 18,
                "document_id": "B917CB0BA5A2D247C9119C8AE91FE97C",
                "headline": "After Jensen Huang Criticized US Export Curbs, Nvidia Set To Launch Cheaper Blackwell AI Chip For China Amid Market Share Slide: Report",
                "ts": "2025-05-26T10:41:48+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/45605521?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 1,
                "text": "Nvidia Corp. (NASDAQ:NVDA) will launch a significantly cheaper artificial intelligence chip for China's market, priced between $6,500 and $8,000, as the company adapts to ongoing U.S. export restrictions that have decimated its Chinese market share.\nWhat Happened: The new graphics processing unit, based on Nvidia's latest Blackwell architecture, represents a dramatic price reduction from the company's recently banned H20 model, which sold for $10,000 to $12,000. Mass production could begin as early as June, Reuters reported, citing sources.",
                "highlights": [
                    {"pnum": 1, "snum": 1},
                    {"pnum": 2, "snum": 1},
                    {"pnum": 2, "snum": 2},
                ],
            },
            "847BB10E2B1775363E80B7334C4B288B-11": {
                "ref_id": 2,
                "document_id": "847BB10E2B1775363E80B7334C4B288B",
                "headline": "5 things to know for Sept. 3: China, War on drugs, Epstein files, RFK Jr., Google",
                "ts": "2025-09-03T10:33:00+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "2435A4",
                "source_name": "CNN",
                "source_rank": 0,
                "url": "https://www.cnn.com/2025/09/03/us/5-things-to-know-for-sept-3-china-war-on-drugs-epstein-files-rfk-jr-google",
                "chunk_id": 11,
                "text": 'In a landmark antitrust ruling, a federal judge has decided that Google will not be forced to sell off its Android operating system or Chrome browser. US District Court Judge Amit Mehta also said he had accepted some of Google\'s proposed remedies. For example, the tech company will need to make certain search data available to qualified competitors to promote competition. And, Google will be barred from entering into or maintaining exclusive contracts related to the distribution of services like Chrome, Search, the Google Assistant and its Gemini app. In a statement, the Justice Department said the ruling "recognizes the need for remedies that will pry open the market for general search services."',
                "highlights": [
                    {"pnum": 29, "snum": 1},
                    {"pnum": 29, "snum": 2},
                    {"pnum": 29, "snum": 3},
                    {"pnum": 29, "snum": 4},
                    {"pnum": 29, "snum": 5},
                ],
            },
            "C66C4028F577CB638A16C9569EF053E0-1": {
                "ref_id": 6,
                "document_id": "C66C4028F577CB638A16C9569EF053E0",
                "headline": "Alphabet to Pour $500 Million Into Sweeping Internal Reforms (2)",
                "ts": "2025-06-02T17:25:30+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "208421",
                "source_name": "Bloomberg News",
                "source_rank": 0,
                "url": "https://news.bloomberglaw.com/esg/alphabet-to-pour-500-million-into-sweeping-internal-reforms",
                "chunk_id": 1,
                "text": "New compliance effort would encompass more than antitrust\nChanges would include committees, processes, monitoring\nAlphabet Inc. has agreed to spend $500 million to improve its global regulatory compliance structure as a proposed resolution to a shareholder suit stemming from US antitrust allegations, according to a federal court filing.",
                "highlights": [{"pnum": 1, "snum": 1}, {"pnum": 2, "snum": 1}],
            },
            "7BF67423D8025C2D96028C4D2FEA794F-5": {
                "ref_id": 17,
                "document_id": "7BF67423D8025C2D96028C4D2FEA794F",
                "headline": "Alphabet (Google) shares news on bold $85 billion investment",
                "ts": "2025-07-27T16:29:07+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "29B277",
                "source_name": "Miami Herald (MH)",
                "source_rank": 1,
                "url": "https://www.miamiherald.com/news/business/article311482503.html",
                "chunk_id": 5,
                "text": "Ashkenazi elaborated on the cloud segment's expanding margins, even as the company invests to meet customer demand: \"As we ramp our AI investments, we continue to focus on driving improvements in productivity and efficiency to offset growth in technical infrastructure-related expenses, particularly from higher depreciation.\"\nOn ramping Alphabet's AI investments, strategic discipline\nAlphabet raised its full-year capital expenditure guidance to $85 billion, a sharp increase from prior estimates of $75 billion. Most of the spend will go toward data center expansions, AI chips (TPUs), and technical infrastructure to support both internal needs (like Search and YouTube) and demand from external clients on Google Cloud.",
                "highlights": [
                    {"pnum": 12, "snum": 1},
                    {"pnum": 13, "snum": 1},
                    {"pnum": 14, "snum": 1},
                    {"pnum": 14, "snum": 2},
                ],
            },
            "D38B91991C8F89F937E95795803582E6-11": {
                "ref_id": 18,
                "document_id": "D38B91991C8F89F937E95795803582E6",
                "headline": "Prediction: The Path Is Finally Clear For These 2 Technology Giants to Surpass $4 Trillion Valuations",
                "ts": "2025-09-14T10:58:10+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "7DFD4A",
                "source_name": "Nasdaq",
                "source_rank": 2,
                "url": "https://www.nasdaq.com/articles/prediction-path-finally-clear-these-2-technology-giants-surpass-4-trillion-valuations",
                "chunk_id": 11,
                "text": "Alphabet's cloud business saw sales soar 32% in the most recent quarter, with its operating margin expanding to 21%. Management said it expects to remain supply constrained into 2026, as it builds out data centers as quickly as possible. That bodes well for continued revenue growth and margin expansion from here.",
                "highlights": [
                    {"pnum": 17, "snum": 1},
                    {"pnum": 17, "snum": 2},
                    {"pnum": 17, "snum": 3},
                ],
            },
            "04211BBDF32804844D5BB05D67D00D3F-6": {
                "ref_id": 3,
                "document_id": "04211BBDF32804844D5BB05D67D00D3F",
                "headline": "Amazon investors again reject all shareholder proposals",
                "ts": "2025-05-21T17:14:32+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "7490C8",
                "source_name": "BNN Bloomberg",
                "source_rank": 0,
                "url": "https://www.bnnbloomberg.ca/investing/2025/05/21/amazon-investors-again-reject-all-shareholder-proposals/",
                "chunk_id": 6,
                "text": "Shareholders voted against a resolution that would have required the company to create a report on risks presented by advertising, in an effort to keep it politically neutral. Also rejected was a proposal soliciting a report on warehouse working conditions, a perennial source of criticism of the company.",
                "highlights": [{"pnum": 10, "snum": 1}, {"pnum": 10, "snum": 2}],
            },
            "E898B75C55FA926D29A67AAF04A55993-1": {
                "ref_id": 20,
                "document_id": "E898B75C55FA926D29A67AAF04A55993",
                "headline": "Amazon CEO Jassy says AI will reduce its corporate workforce in the next few years",
                "ts": "2025-06-18T14:02:22+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "D904DE",
                "source_name": "Associated Press",
                "source_rank": 0,
                "url": "https://apnews.com/article/amazon-jassy-ai-alexa-workforce-7eea6387e97b84f1f239af2538de5ee9",
                "chunk_id": 1,
                "text": 'Amazon CEO Andy Jassy anticipates generative artificial intelligence will reduce its corporate workforce in the next few years as the online giant begins to increase its usage of the technology.\n"We will need fewer people doing some of the jobs that are being done today, and more people doing other types of jobs," Jassy said in a message to employees. "It\'s hard to know exactly where this nets out over time, but in the next few years, we expect that this will reduce our total corporate workforce as we get efficiency gains from using AI extensively across the company."',
                "highlights": [
                    {"pnum": 1, "snum": 1},
                    {"pnum": 2, "snum": 1},
                    {"pnum": 2, "snum": 2},
                ],
            },
            "7BA88ECD4CDDDD5F25FB6E5B7623B0EE-1": {
                "ref_id": 35,
                "document_id": "7BA88ECD4CDDDD5F25FB6E5B7623B0EE",
                "headline": "Amazon just made it easier to order fresh food",
                "ts": "2025-08-13T13:10:59+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "2435A4",
                "source_name": "CNN",
                "source_rank": 0,
                "url": "https://us.cnn.com/2025/08/13/food/amazon-grocery-delivery-expansion",
                "chunk_id": 1,
                "text": 'New York\n  -\nAmazon is rolling out same-day delivery of fresh food to more than 1,000 cities, a sign that it\'s finally finding success with its grocery business after years of shifting strategies.\nIn a move that Amazon describes in a press release as one of its "most significant grocery expansions," customers can now order perishable food items, including dairy, meat and seafood, alongside their typical Amazon orders and get them on the same day.',
                "highlights": [
                    {"pnum": 6, "snum": 1},
                    {"pnum": 7, "snum": 1},
                    {"pnum": 8, "snum": 1},
                ],
            },
            "1371BF3D4E067FABA429CF5E4E86EED0-1": {
                "ref_id": 39,
                "document_id": "1371BF3D4E067FABA429CF5E4E86EED0",
                "headline": "Amazon's FTC Trial Over Alleged 'Dark Patterns' Of Prime Subscription Cancellation Practices Kicks Off",
                "ts": "2025-09-23T10:08:26+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/47812945?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 1,
                "text": "The Federal Trade Commission (FTC) has initiated its legal battle against Amazon.com Inc. (NASDAQ:AMZN) over the company's Prime subscription cancellation practices.\nFTC Trial Targets Amazon Over Prime 'Dark Pattern' Practices\nThe FTC trial against Amazon began on Monday, with the company's Prime subscription practices under scrutiny, CNN reported. The lawsuit, filed in 2023, alleges that Amazon used manipulative user interface designs, or 'dark patterns,' to mislead consumers into enrolling in Prime and create obstacles for them when trying to cancel.",
                "highlights": [
                    {"pnum": 1, "snum": 1},
                    {"pnum": 2, "snum": 1},
                    {"pnum": 3, "snum": 1},
                    {"pnum": 3, "snum": 2},
                ],
            },
            "1371BF3D4E067FABA429CF5E4E86EED0-2": {
                "ref_id": 40,
                "document_id": "1371BF3D4E067FABA429CF5E4E86EED0",
                "headline": "Amazon's FTC Trial Over Alleged 'Dark Patterns' Of Prime Subscription Cancellation Practices Kicks Off",
                "ts": "2025-09-23T10:08:26+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "5A5702",
                "source_name": "Benzinga",
                "source_rank": 0,
                "url": "https://www.benzinga.com/node/47812945?utm_campaign=partner_feed&utm_medium=feed&utm_source=ravenpack",
                "chunk_id": 2,
                "text": 'Check out the current price of AMZN stock here.\nThe trial is projected to run for roughly a month, beginning with jury selection on Monday and opening arguments set for Tuesday. Should Amazon be found liable, the judge will decide the damages the company must pay.\nThe FTC claims that Amazon used a complicated cancellation system, known internally as "Iliad Flow," with multiple steps intended to discourage customers from canceling. The agency also alleges that Amazon made joining Prime simple while frequently hiding recurring billing details in fine print.',
                "highlights": [
                    {"pnum": 4, "snum": 1},
                    {"pnum": 5, "snum": 1},
                    {"pnum": 5, "snum": 2},
                    {"pnum": 6, "snum": 1},
                    {"pnum": 6, "snum": 2},
                ],
            },
            "AA6E7AE1225136AB75FACEA3CC8D603C-15": {
                "ref_id": 3,
                "document_id": "AA6E7AE1225136AB75FACEA3CC8D603C",
                "headline": "MDB Q2 Deep Dive: Atlas Growth, Upmarket Strategy, and AI Positioning Drive Outlook",
                "ts": "2025-08-28T17:08:35+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "E5AA62",
                "source_name": "Yahoo! Finance",
                "source_rank": 2,
                "url": "https://finance.yahoo.com/news/mdb-q2-deep-dive-atlas-134045485.html",
                "chunk_id": 15,
                "text": "Balanced investment strategy: MongoDB plans to maintain its focus on improving operating margins while selectively increasing investment in R&D and go-to-market programs, especially for developer awareness and tooling related to application modernization and AI integration. Management noted that efficiency initiatives and higher revenue expectations allow for incremental investment without sacrificing profitability.",
                "highlights": [{"pnum": 27, "snum": 1}, {"pnum": 27, "snum": 2}],
            },
            "17D930A64240A9A212340E58EE241179-6": {
                "ref_id": 5,
                "document_id": "17D930A64240A9A212340E58EE241179",
                "headline": "Can AI-Powered Tools Position MongoDB for Sustained Revenue Growth?",
                "ts": "2025-09-17T20:03:18+00:00",
                "document_scope": "news",
                "language": "English",
                "source_key": "E5AA62",
                "source_name": "Yahoo! Finance",
                "source_rank": 2,
                "url": "https://finance.yahoo.com/news/ai-powered-tools-position-mongodb-175400332.html",
                "chunk_id": 6,
                "text": "MongoDB faces competition from Snowflake SNOW and ServiceNow NOW. Snowflake is integrating Cortex and Cortex Search to run AI and analytics workloads natively on the Snowflake platform, expanding customer adoption and revenue growth. ServiceNow is embedding generative AI tools like AI Search and Now Assist across the Now Platform, positioning ServiceNow to deepen workflow usage and attract long-term commitments. Both Snowflake and ServiceNow are pursuing AI integration to broaden workloads and strengthen enterprise traction, mirroring MongoDB's strategy.",
                "highlights": [
                    {"pnum": 6, "snum": 1},
                    {"pnum": 6, "snum": 2},
                    {"pnum": 6, "snum": 3},
                    {"pnum": 6, "snum": 4},
                ],
            },
        },
    },
)
