version: 2
multi-ecosystem-groups:
  briefs-service:
    schedule:
      interval: "cron"
      cronob: "0 8 * * 1" # "At 08:00 on Monday."
    assignees: ["@Bigdata-com/data-science"]
    labels: ["bug"]
updates:
  - package-ecosystem: "uv"
    multi-ecosystem-group: "briefs-service"
    directory: "/"
    patterns: ["bigdata-client"]
  - package-ecosystem: "docker"
    multi-ecosystem-group: "briefs-service"
    directory: "/"
    patterns: ["*"]